---
# Input
samples_file: "/scicore/home/zavolan/GROUP/RNA_oxidation/output/start_samples.tsv"

# Output
output_dir: "/scicore/home/zavolan/GROUP/RNA_oxidation/output/"
local_log: "/scicore/home/zavolan/GROUP/RNA_oxidation/output/local_log/"
cluster_log: "/scicore/home/zavolan/GROUP/RNA_oxidation/temp_dir/slurm/"

###############################################################################
# General settings
###############################################################################

organism: "human"
genome_file: "/scicore/home/zavolan/GROUP/Genomes/homo_sapiens/GRCh38.primary_assembly.genome.fa"
gtf_file: "/scicore/home/zavolan/GROUP/Genomes/homo_sapiens/hg38_v42/enriched.gencode.v42.annotation.gtf"
CDS_segments_gtf: "/scicore/home/zavolan/GROUP/Genomes/homo_sapiens/hg38_v42/constitutive_exonic_regions_in_genes.bed"
gene_type_segments_gtf: "/scicore/home/zavolan/GROUP/Genomes/homo_sapiens/hg38_v42/constitutive_exonic_regions_in_genes.collapsed.gtf"
chromosomes: "chr11"

###############################################################################
# PAQR config
###############################################################################

# Processed and filtered PolyASite Atlas
tandem_pas: "/scicore/home/zavolan/GROUP/Genomes/homo_sapiens/hg38_v42/tandem_pas.terminal_exons.unstranded.bed"

# number of nucleotides for which the coverage profile is extended
# and obtained downstream of each annotated exon end
PAQ_coverage_downstream_extension: "400"

# minimum distance between the exon start and the most proximal poly(A) site
# (for exons with distances below the cutoff the upstream extension
# of the coverage is calculated)
PAQ_min_distance_start_to_proximal: "50"

# IMPORTANT:
# denote if the BAM files come from unstranded sequencing
# By default paired-end sequencing with read1 - reverse orientation,
# read2 - forward orientation is assumed.
# Single-stranded data with the reads in sense direction are processed properly too
# PAQR does not support single-end data in reverse orientation.
PAQ_coverage_unstranded: "no"

# minimum length of the region that needs to be available
# to calculate a mean coverage and the mean squared error
PAQ_min_length_mean_coverage: "50"

# minimum mean coverage required for an exon to be considered in the analysis
PAQ_min_mean_exon_coverage: "0"

# length of the region downstream of the exon,
# necessary to search for zero coverage downstream of the distal site
PAQ_distal_downstream_extension: "400"

# maximum percentage of the coverage at the exon start
# which is allowed for the mean coverage in the downstream region
# of a valid distal site
PAQ_max_mean_coverage: "1"

# distance until which poly(A) clusters are merged
PAQ_cluster_distance: "50"

# upstream extension added to the poly(A) cluster's end
# during the check for global break points 
PAQ_upstream_cluster_extension: "400"

# upper limit on the ratio of coverage mean squared error values
# after and before including a new break point 
PAQ_coverage_mse_ratio_limit: "0.5"

# expected RNA-Seq fragment length (from BioAnalyzer)
PAQ_fragment_length: "350"